// AI Auto-Fix Engine — สร้างไฟล์/โค้ดแก้จริงจากปัญหาที่ตรวจพบ
// ผลลัพธ์: [{ id, forCheck, filename, language, title, description, content, howTo }]
import { aiGenerateMeta, aiAvailable } from './ai.js';
import { aiFixPageVerified } from './pagefix.js';

const esc = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export async function generateFixes(audit, site) {
  const fixes = [];
  const failedIds = new Set(audit.checks.filter(c => c.status !== 'pass' && c.status !== 'info').map(c => c.id));
  const pages = site.pages.filter(p => p.title !== undefined && !p.nonHtml && !p.blocked && p.status === 200);
  const home = pages.find(p => { try { return new URL(p.url).pathname === '/'; } catch { return false; } }) || pages[0];
  const origin = site.origin;
  const hostname = (() => { try { return new URL(origin).hostname.replace(/^www\./, ''); } catch { return origin; } })();
  const brand = home?.metas?.['og:site_name'] || (home?.title || hostname).split(/[|\-–]/)[0].trim() || hostname;

  // ── 1. robots.txt ที่ถูกต้อง (เปิด AI bots + อ้าง sitemap) ──
  if (failedIds.has('robots-missing') || failedIds.has('robots-blocks-all') || failedIds.has('robots-blocks-section') || failedIds.has('geo-bot-access') || failedIds.has('robots-sitemap')) {
    fixes.push({
      id: 'fix-robots', forCheck: 'robots / geo-bot-access', filename: 'robots.txt', language: 'text',
      title: 'robots.txt ฉบับแก้แล้ว (เปิดรับทั้ง Google และ AI bots)',
      description: 'อนุญาต search bot + AI bot ทุกตัวที่ควรเข้า บล็อกเฉพาะส่วน admin และอ้างถึง sitemap',
      howTo: 'วางไฟล์นี้แทน robots.txt เดิมที่ root ของเว็บ (เช็กก่อนว่า path ที่บล็อกตรงกับระบบหลังบ้านของคุณ)',
      content: `# robots.txt — generated by AI SEO Audit Pro
# เปิดรับ search engines ทั้งหมด
User-agent: *
Disallow: /admin/
Disallow: /wp-admin/
Disallow: /cart
Disallow: /checkout
Allow: /

# เปิดรับ AI bots อย่างชัดเจน (GEO — ให้แบรนด์ปรากฏใน AI answers)
User-agent: GPTBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

Sitemap: ${origin}/sitemap.xml
`,
    });
  }

  // ── 2. sitemap.xml จากหน้าที่ crawl เจอจริง ──
  if (failedIds.has('sitemap-exists') || failedIds.has('sitemap-coverage')) {
    const urls = [...new Set(pages.map(p => p.finalUrl || p.url))];
    fixes.push({
      id: 'fix-sitemap', forCheck: 'sitemap-exists', filename: 'sitemap.xml', language: 'xml',
      title: `sitemap.xml สร้างจากหน้าจริงที่พบ (${urls.length} URLs)`,
      description: 'สร้างจากการ crawl จริง — ทุก URL ตอบ 200 และเป็น HTML',
      howTo: 'วางที่ root ของเว็บ แล้ว submit ใน Google Search Console → Sitemaps',
      content: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${esc(u)}</loc></url>`).join('\n')}
</urlset>
`,
    });
  }

  // ── 3. Organization + WebSite JSON-LD ──
  if (failedIds.has('schema-org') || failedIds.has('jsonld-missing') || failedIds.has('geo-entity')) {
    fixes.push({
      id: 'fix-org-schema', forCheck: 'schema-org / geo-entity', filename: 'organization-schema.html', language: 'html',
      title: 'Organization + WebSite schema (JSON-LD)',
      description: 'ข้อมูล entity ของแบรนด์ให้ Google Knowledge Panel และ AI engines — เติมข้อมูลจริงในช่อง TODO',
      howTo: 'วางใน <head> ของทุกหน้า (layout หลัก) แล้วเติม logo, ที่อยู่, social links จริง',
      content: `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "${origin}/#organization",
      "name": "${esc(brand)}",
      "url": "${origin}/",
      "logo": { "@type": "ImageObject", "url": "${origin}/logo.png" },
      "description": "TODO: อธิบายธุรกิจ 1-2 ประโยค มีคีย์เวิร์ดหลัก",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "TODO",
        "addressLocality": "TODO เช่น Bangkok",
        "addressCountry": "TH"
      },
      "sameAs": [
        "TODO: https://www.facebook.com/...",
        "TODO: https://www.linkedin.com/company/...",
        "TODO: https://www.youtube.com/@..."
      ]
    },
    {
      "@type": "WebSite",
      "@id": "${origin}/#website",
      "url": "${origin}/",
      "name": "${esc(brand)}",
      "publisher": { "@id": "${origin}/#organization" },
      "inLanguage": "th"
    }
  ]
}
</script>`,
    });
  }

  // ── 4. FAQ schema template (GEO) ──
  if (failedIds.has('geo-faq-schema') || failedIds.has('geo-qa-content')) {
    fixes.push({
      id: 'fix-faq-schema', forCheck: 'geo-faq-schema', filename: 'faq-schema.html', language: 'html',
      title: 'FAQ section + FAQPage schema (อาวุธลับ GEO)',
      description: 'โครง FAQ ที่ AI Overview / ChatGPT ดึงไปตอบได้ตรงที่สุด — แก้คำถาม-คำตอบให้ตรงธุรกิจ',
      howTo: 'วาง HTML ในหน้าบริการหลัก และ JSON-LD ใน <head> ของหน้าเดียวกัน (คำถาม-คำตอบต้องตรงกับที่แสดงบนหน้า)',
      content: `<!-- ส่วนแสดงผลบนหน้า -->
<section class="faq">
  <h2>คำถามที่พบบ่อย</h2>
  <h3>TODO: คำถามที่ลูกค้าถามบ่อยที่สุด เช่น "${esc(brand)} ให้บริการอะไรบ้าง?"</h3>
  <p>TODO: คำตอบกระชับ 2-3 ประโยค ตอบตรงคำถามในประโยคแรก</p>
  <h3>TODO: คำถามที่ 2 เช่น "ราคาเริ่มต้นเท่าไหร่?"</h3>
  <p>TODO: คำตอบ</p>
  <h3>TODO: คำถามที่ 3</h3>
  <p>TODO: คำตอบ</p>
</section>

<!-- Schema ใน <head> -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "TODO: คำถามที่ 1 (ต้องตรงกับบนหน้า)",
      "acceptedAnswer": { "@type": "Answer", "text": "TODO: คำตอบ" }
    },
    {
      "@type": "Question",
      "name": "TODO: คำถามที่ 2",
      "acceptedAnswer": { "@type": "Answer", "text": "TODO: คำตอบ" }
    },
    {
      "@type": "Question",
      "name": "TODO: คำถามที่ 3",
      "acceptedAnswer": { "@type": "Answer", "text": "TODO: คำตอบ" }
    }
  ]
}
</script>`,
    });
  }

  // ── 5. llms.txt ──
  if (failedIds.has('geo-llms-txt')) {
    const topPages = pages.slice(0, 10).map(p => `- [${(p.title || p.url).slice(0, 70)}](${p.finalUrl || p.url})`).join('\n');
    fixes.push({
      id: 'fix-llms-txt', forCheck: 'geo-llms-txt', filename: 'llms.txt', language: 'markdown',
      title: 'llms.txt — ไกด์สำหรับ AI (นำหน้าคู่แข่ง 99%)',
      description: 'มาตรฐานใหม่ที่บอก LLM ว่าเว็บคุณคือใคร หน้าไหนสำคัญ — สร้างโครงจากหน้าที่ crawl เจอจริง',
      howTo: 'เติมคำอธิบายใน TODO แล้ววางที่ root: ' + origin + '/llms.txt',
      content: `# ${brand}

> TODO: อธิบายธุรกิจ 1-2 ประโยค ชัดๆ ว่าคุณคือใคร ขายอะไร ให้ใคร

## หน้าสำคัญ

${topPages}

## ข้อมูลติดต่อ

- เว็บไซต์: ${origin}
- TODO: อีเมล/เบอร์ติดต่อ
`,
    });
  }

  // ── 6. Canonical tags รายหน้า ──
  if (failedIds.has('canonical-missing')) {
    const need = pages.filter(p => !p.canonical);
    fixes.push({
      id: 'fix-canonical', forCheck: 'canonical-missing', filename: 'canonical-tags.html', language: 'html',
      title: `Canonical tags สำหรับ ${need.length} หน้าที่ขาด`,
      description: 'แต่ละหน้าชี้ canonical ไป URL หลักของตัวเอง — กัน duplicate content',
      howTo: 'วางแต่ละบรรทัดใน <head> ของหน้านั้นๆ (ถ้าใช้ framework ให้ตั้งใน layout/head config)',
      content: need.map(p => `<!-- ${p.url} -->\n<link rel="canonical" href="${esc((p.finalUrl || p.url).replace(/\?.*$/, ''))}">`).join('\n\n'),
    });
  }

  // ── 7. Security headers (nginx + Apache) ──
  if (failedIds.has('security-headers') || failedIds.has('compression')) {
    fixes.push({
      id: 'fix-headers', forCheck: 'security-headers / compression', filename: 'server-headers.conf', language: 'nginx',
      title: 'Security headers + compression config',
      description: 'config สำหรับ nginx (และ .htaccess สำหรับ Apache อยู่ท้ายไฟล์)',
      howTo: 'nginx: ใส่ใน server block แล้ว reload | Apache: ใช้ส่วน .htaccess',
      content: `# ─── nginx — ใส่ใน server { } block ───
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# เปิด compression
gzip on;
gzip_types text/html text/css application/javascript application/json image/svg+xml;
gzip_min_length 1024;
# ถ้า build nginx มากับ brotli module:
# brotli on; brotli_types text/html text/css application/javascript application/json image/svg+xml;

# ─── Apache (.htaccess) ───
# Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
# Header always set X-Content-Type-Options "nosniff"
# Header always set X-Frame-Options "SAMEORIGIN"
# Header always set Referrer-Policy "strict-origin-when-cross-origin"
# AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json
`,
    });
  }

  // ── 8. SSR guide ถ้าเจอ SPA shell ──
  if (failedIds.has('spa-shell') || failedIds.has('geo-spa-risk')) {
    const fw = home ? Object.entries(home.frameworkMarkers || {}).filter(([, v]) => v).map(([k]) => k) : [];
    fixes.push({
      id: 'fix-ssr', forCheck: 'spa-shell', filename: 'enable-ssr-guide.md', language: 'markdown',
      title: `เปิด SSR/Pre-render (${fw.join(', ') || 'JS framework'}) — การแก้ที่สำคัญที่สุด`,
      description: 'ปัญหาใหญ่สุดของเว็บนี้: เนื้อหา render ด้วย JS เท่านั้น ทำให้ AI bot และ Google รอบแรกเห็นหน้าว่าง',
      howTo: 'ส่งให้ทีม dev — มีขั้นตอนตามแต่ละ framework',
      content: `# เปิด Server-Side Rendering — แก้ปัญหาใหญ่ที่สุดของเว็บนี้

## ทำไมต้องแก้ (อธิบายให้ผู้บริหารฟังได้)
ตอนนี้ HTML ที่เซิร์ฟเวอร์ส่งออกมาเป็น "เปลือกเปล่า" — เนื้อหา หัวข้อ ลิงก์ ทั้งหมดถูกสร้างด้วย JavaScript ในเบราว์เซอร์
- Googlebot รอบแรกเห็นหน้าว่าง → จัดอันดับช้าและต่ำกว่าที่ควร
- AI bots (GPTBot, ClaudeBot, PerplexityBot) **ไม่รัน JavaScript เลย** → แบรนด์ไม่มีทางถูก ChatGPT/Perplexity อ้างถึง

## วิธีแก้ตาม framework

### Nuxt (Vue)
\`\`\`js
// nuxt.config.ts
export default defineNuxtConfig({
  ssr: true,                    // ต้องเป็น true
  // ถ้าเว็บเป็น content site ใช้ static generate ได้เลย — เร็วสุด ปลอดภัยสุด:
  // npm run generate  → ได้ HTML ไฟล์จริงทุกหน้า
})
\`\`\`
Deploy: ถ้าใช้ CDN/CloudFront ต้องชี้ origin ไปที่ Node server (SSR) หรือโฟลเดอร์ .output/public (generate)

### Next.js (React)
- ใช้ App Router + Server Components (default คือ SSR อยู่แล้ว)
- หน้า static ใช้ \`export const dynamic = 'force-static'\`
- เช็กว่าไม่ได้ครอบทุกอย่างด้วย 'use client'

### ไม่อยากแตะ framework? ใช้ Pre-rendering แทน
- Prerender.io หรือ Rendertron — ดัก bot แล้วส่งหน้า render แล้วให้
- ง่ายกว่า แต่เป็นการแก้ชั่วคราว แนะนำ SSR จริงในระยะยาว

## ตรวจรับงาน (Definition of Done)
1. \`curl -s ${origin} | grep '<h1'\` ต้องเห็น H1 พร้อมข้อความจริง
2. ดู view-source ของหน้าแรก ต้องเห็นเนื้อหา ไม่ใช่ div ว่าง
3. รัน audit นี้ซ้ำ — ข้อ "SPA เปลือกเปล่า" ต้องเป็น PASS
`,
    });
  }

  // ── 9. Meta title/description ใหม่ (AI เขียน) ──
  const needMeta = pages.filter(p => !p.title || !p.metas['description'] || (p.title && p.title.length > 60));
  if (needMeta.length && (failedIds.has('title-missing') || failedIds.has('desc-missing') || failedIds.has('title-length') || failedIds.has('title-duplicate'))) {
    const gen = await aiGenerateMeta(needMeta, origin);
    const rows = (gen.pages || []).map(g =>
      `<!-- ═══ ${g.url} ═══\n     เหตุผล: ${g.reason || '-'} -->\n<title>${esc(g.title)}</title>\n<meta name="description" content="${esc(g.description)}">`
    ).join('\n\n');
    fixes.push({
      id: 'fix-meta', forCheck: 'title/description', filename: 'meta-tags-rewritten.html', language: 'html',
      title: `Meta title + description เขียนใหม่ ${gen.pages?.length || 0} หน้า ${gen.source === 'ai' ? '(AI เขียนจากเนื้อหาจริง)' : '(สร้างจาก H1 — ใส่ AI key เพื่อให้เขียนแบบมือโปร)'}`,
      description: 'เขียนตามหลัก: title 30-60 ตัวอักษร นำด้วยคีย์เวิร์ด, description มี benefit + CTA',
      howTo: 'นำไปวางแทนของเดิมในแต่ละหน้า ตรวจความถูกต้องของแบรนด์/ข้อเสนอก่อนใช้จริง',
      content: rows || '(ไม่มีหน้าที่ต้องแก้)',
      aiGenerated: gen.source === 'ai',
    });
  }

  // ── 10. hreflang ──
  if (failedIds.has('hreflang')) {
    const thPages = pages.filter(p => /\/th\//.test(p.url)).slice(0, 5);
    const enPages = pages.filter(p => /\/en\//.test(p.url)).slice(0, 5);
    if (thPages.length || enPages.length) {
      fixes.push({
        id: 'fix-hreflang', forCheck: 'hreflang', filename: 'hreflang-tags.html', language: 'html',
        title: 'hreflang tags สำหรับเว็บหลายภาษา',
        description: 'ตัวอย่างจาก URL จริงที่พบ — ทุกหน้าต้องอ้างถึงกันครบทุกภาษา + x-default',
        howTo: 'วางใน <head> ของทุกหน้า (แก้ URL ให้ตรงคู่ภาษาของหน้านั้น)',
        content: `<!-- ตัวอย่างสำหรับหน้าแรก — ทำซ้ำทุกหน้าที่มี 2 ภาษา -->
<link rel="alternate" hreflang="th" href="${origin}/th/">
<link rel="alternate" hreflang="en" href="${origin}/en/">
<link rel="alternate" hreflang="x-default" href="${origin}/">`,
      });
    }
  }

  // ── 11. หน้าเว็บฉบับแก้แล้วทั้งหน้า (showcase ของ Auto-Fix) ──
  if (site.homeHtml && home) {
    const issues = audit.checks
      .filter(c => (c.status === 'fail' || c.status === 'warn') && c.severity !== 'low')
      .map(c => ({ severity: c.severity, title: c.title, detail: c.detail.slice(0, 150) }))
      .slice(0, 18);
    if (aiAvailable()) {
      try {
        const r = await aiFixPageVerified(site.homeHtml, site.homeHtmlUrl, brand);
        fixes.unshift({
          id: 'fix-page', forCheck: 'ทุกปัญหาบนหน้าแรก', filename: 'index.fixed.html', language: 'html', preview: true,
          title: `หน้าเว็บฉบับแก้แล้ว — พิสูจน์ด้วยการตรวจซ้ำ: ปัญหา ${r.before.count} → ${r.after.count} ข้อ (ร้ายแรง ${r.before.high} → ${r.after.high})${r.verified ? ' ผ่านเกณฑ์' : ''}`,
          description: `AI แก้ ${r.passes} รอบจาก HTML จริงของ ${site.homeHtmlUrl} แล้วระบบรัน rule engine ตรวจซ้ำเพื่อยืนยันผล — ทุกจุดที่แก้มี comment <!-- FIXED --> กำกับ${r.after.count ? ' | ที่เหลือ: ' + r.after.issues.map(i => i.msg).join(', ') : ''}`,
          howTo: 'กด "เปิดดูตัวอย่าง" เทียบกับหน้าเดิม แล้วส่งไฟล์ให้ทีม dev นำไปใช้ (ตรวจความถูกต้องของเนื้อหาก่อน deploy จริง)',
          content: r.fixedHtml,
          aiGenerated: true, verified: r.verified,
        });
      } catch (e) { /* AI ล้มเหลว — ใช้ fallback ด้านล่าง */ }
    }
    if (!fixes.some(f => f.id === 'fix-page')) {
      // Fallback ไม่มี AI key: สร้าง <head> ฉบับสมบูรณ์จากข้อมูลที่ crawl ได้
      const title = home.title || `${brand} — TODO: ใส่ title 30-60 ตัวอักษร`;
      const desc = home.metas?.['description'] || (home.textSample || '').slice(0, 150) || 'TODO: meta description 80-160 ตัวอักษร';
      fixes.unshift({
        id: 'fix-page', forCheck: 'head ของหน้าแรก', filename: 'head.fixed.html', language: 'html',
        title: 'ส่วน <head> ฉบับแก้ครบของหน้าแรก (ใส่ AI key เพื่อให้แก้ทั้งหน้า)',
        description: 'head สมบูรณ์: title, description, canonical, OG, Twitter, viewport, JSON-LD — ประกอบจากข้อมูลจริงที่ crawl ได้',
        howTo: 'แทนที่ head เดิมของหน้าแรก แล้วเช็คช่อง TODO — ถ้าใส่ ANTHROPIC_API_KEY/OPENAI_API_KEY ระบบจะให้ AI แก้ทั้งหน้าแบบมี comment กำกับทุกจุด',
        content: `<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${esc((home.finalUrl || home.url).replace(/\?.*$/, ''))}">
  <link rel="icon" href="/favicon.ico">

  <meta property="og:type" content="website">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:image" content="${origin}/og-image.jpg">
  <meta property="og:url" content="${esc(home.finalUrl || home.url)}">
  <meta name="twitter:card" content="summary_large_image">

  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "${esc(brand)}",
    "url": "${origin}/",
    "logo": "${origin}/logo.png"
  }
  </script>
</head>`,
      });
    }
  }

  return { fixes, aiUsed: aiAvailable() };
}
