// lib/references.js — Reference Authority: ทุก check id → มาตรฐานอ้างอิง + tier + confidence + URL จริง
// ตอบลูกค้า "อ้างอิงจากอะไร" ได้ทุกข้อ · auto-generated จาก docs/skill-system-plan.html (verify ลิงก์ 88/88 แล้ว)
// tier 1 Official Standard · 2 Search Engine Guidance · 3 Industry Best Practice · 4 AI/LLM Best Practice

export const TIER_TYPE = {
  1: 'Official Standard',
  2: 'Search Engine Guidance',
  3: 'Industry Best Practice',
  4: 'AI/LLM Best Practice',
};

// แหล่งอ้างอิง: key → [label, url เอกสารตัวจริง]
const REF = {
  gTitle: ["Google: Influencing title links", "https://developers.google.com/search/docs/appearance/title-link"],
  gSnippet: ["Google: Control your snippets", "https://developers.google.com/search/docs/appearance/snippet"],
  gStarter: ["Google: SEO Starter Guide", "https://developers.google.com/search/docs/fundamentals/seo-starter-guide"],
  gHelpful: ["Google: Creating helpful content", "https://developers.google.com/search/docs/fundamentals/creating-helpful-content"],
  gCanonical: ["Google: Consolidate duplicate URLs", "https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls"],
  gHttps: ["Google: HTTPS as a ranking signal", "https://developers.google.com/search/blog/2014/08/https-as-ranking-signal"],
  gRobotsIntro: ["Google: Intro to robots.txt", "https://developers.google.com/search/docs/crawling-indexing/robots/intro"],
  gRobotsMeta: ["Google: robots meta tag", "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag"],
  gBlockIndex: ["Google: Block indexing (noindex)", "https://developers.google.com/search/docs/crawling-indexing/block-indexing"],
  gSitemapBuild: ["Google: Build and submit a sitemap", "https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap"],
  gSitemapOverview: ["Google: Sitemaps overview", "https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview"],
  gHreflang: ["Google: Localized versions (hreflang)", "https://developers.google.com/search/docs/specialty/international/localized-versions"],
  gRedirects: ["Google: Redirects and Google Search", "https://developers.google.com/search/docs/crawling-indexing/301-redirects"],
  gCrawlers: ["Google: Overview of Google crawlers", "https://developers.google.com/crawling/docs/crawlers-fetchers/overview-google-crawlers"],
  gHttpErrors: ["Google: HTTP status & network errors", "https://developers.google.com/crawling/docs/troubleshooting/http-status-codes"],
  gStructured: ["Google: Intro to structured data", "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data"],
  gBreadcrumb: ["Google: Breadcrumb structured data", "https://developers.google.com/search/docs/appearance/structured-data/breadcrumb"],
  gOrg: ["Google: Organization structured data", "https://developers.google.com/search/docs/appearance/structured-data/organization"],
  gFaq: ["Google: Changes to FAQ rich results (2023)", "https://developers.google.com/search/blog/2023/08/howto-faq-changes"],
  gLinks: ["Google: Make your links crawlable", "https://developers.google.com/search/docs/crawling-indexing/links-crawlable"],
  gCwv: ["Google: Core Web Vitals report", "https://developers.google.com/search/docs/appearance/core-web-vitals"],
  gFavicon: ["Google: Define a favicon", "https://developers.google.com/search/docs/appearance/favicon-in-search"],
  gJsRendering: ["Google: JavaScript SEO basics", "https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics"],
  gMobile: ["Google: Mobile-first indexing", "https://developers.google.com/search/docs/crawling-indexing/mobile/mobile-sites-mobile-first-indexing"],
  gUrl: ["Google: URL structure best practices", "https://developers.google.com/search/docs/crawling-indexing/url-structure"],
  gNoKeywords: ["Google: We don't use the keywords meta tag", "https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag"],
  gQrg: ["Google: Search Quality Rater Guidelines (PDF)", "https://static.googleusercontent.com/media/guidelines.raterhub.com/en//searchqualityevaluatorguidelines.pdf"],
  htmlTitle: ["HTML Standard: the title element", "https://html.spec.whatwg.org/multipage/semantics.html#the-title-element"],
  htmlHeadings: ["HTML Standard: headings & outlines", "https://html.spec.whatwg.org/multipage/sections.html#headings-and-outlines"],
  htmlDoctype: ["HTML Standard: the DOCTYPE", "https://html.spec.whatwg.org/multipage/syntax.html#the-doctype"],
  htmlCharset: ["HTML Standard: charset declaration", "https://html.spec.whatwg.org/multipage/semantics.html#charset"],
  htmlLang: ["HTML Standard: the lang attribute", "https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes"],
  htmlAlt: ["HTML Standard: alt text requirements", "https://html.spec.whatwg.org/multipage/images.html#alt"],
  htmlImgDim: ["HTML Standard: dimension attributes", "https://html.spec.whatwg.org/multipage/embedded-content-other.html#dimension-attributes"],
  htmlLazy: ["HTML Standard: lazy-loading attribute", "https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes"],
  htmlNoscript: ["HTML Standard: the noscript element", "https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element"],
  htmlObsolete: ["HTML Standard: obsolete features", "https://html.spec.whatwg.org/multipage/obsolete.html"],
  htmlRefresh: ["HTML Standard: meta http-equiv refresh", "https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-refresh"],
  encoding: ["WHATWG: Encoding Standard", "https://encoding.spec.whatwg.org/"],
  jsonld: ["W3C: JSON-LD 1.1", "https://www.w3.org/TR/json-ld11/"],
  schemaOrg: ["Schema.org", "https://schema.org/"],
  schemaBreadcrumb: ["Schema.org: BreadcrumbList", "https://schema.org/BreadcrumbList"],
  schemaOrgType: ["Schema.org: Organization", "https://schema.org/Organization"],
  schemaFaq: ["Schema.org: FAQPage", "https://schema.org/FAQPage"],
  wcagAlt: ["WCAG 2.1: Non-text Content (1.1.1)", "https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html"],
  wcagHeadings: ["WCAG 2.1: Headings and Labels (2.4.6)", "https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html"],
  wcagZoom: ["WCAG 2.1: Resize Text (1.4.4)", "https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html"],
  wcagLang: ["WCAG 2.1: Language of Page (3.1.1)", "https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html"],
  wcagLink: ["WCAG 2.1: Link Purpose (2.4.4)", "https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html"],
  mixedW3C: ["W3C: Mixed Content", "https://www.w3.org/TR/mixed-content/"],
  mdnMixed: ["MDN: Mixed content", "https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Mixed_content"],
  mdnHeaders: ["MDN: HTTP headers", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers"],
  mdnViewport: ["MDN: Viewport meta tag", "https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta/name/viewport"],
  mdnLazy: ["MDN: Lazy loading", "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/Lazy_loading"],
  mdnTls: ["MDN: Transport Layer Security", "https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Transport_Layer_Security"],
  owasp: ["OWASP: Secure Headers Project", "https://owasp.org/www-project-secure-headers/"],
  ogp: ["The Open Graph protocol", "https://ogp.me/"],
  xcards: ["X Developer Docs (Cards)", "https://docs.x.com/overview"],
  sitemapsOrg: ["sitemaps.org: protocol", "https://www.sitemaps.org/protocol.html"],
  rfc9309: ["RFC 9309: Robots Exclusion Protocol", "https://datatracker.ietf.org/doc/html/rfc9309"],
  rfc6596: ["RFC 6596: The Canonical Link Relation", "https://datatracker.ietf.org/doc/html/rfc6596"],
  rfc9110: ["RFC 9110: HTTP Semantics", "https://datatracker.ietf.org/doc/html/rfc9110"],
  rfc9110redir: ["RFC 9110: Redirection 3xx", "https://datatracker.ietf.org/doc/html/rfc9110#section-15.4"],
  rfc9110_404: ["RFC 9110: 404 Not Found", "https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.5"],
  rfc3986: ["RFC 3986: URI Generic Syntax", "https://datatracker.ietf.org/doc/html/rfc3986"],
  rfc8446: ["RFC 8446: TLS 1.3", "https://datatracker.ietf.org/doc/html/rfc8446"],
  wTtfb: ["web.dev: Time to First Byte (TTFB)", "https://web.dev/articles/ttfb"],
  lhCompress: ["Lighthouse: Enable text compression", "https://developer.chrome.com/docs/lighthouse/performance/uses-text-compression"],
  lhRenderBlock: ["Lighthouse: Eliminate render-blocking resources", "https://developer.chrome.com/docs/lighthouse/performance/render-blocking-resources"],
  lhThirdParty: ["Lighthouse: Reduce third-party impact", "https://developer.chrome.com/docs/lighthouse/performance/third-party-summary"],
  lhPayload: ["Lighthouse: Avoid enormous network payloads", "https://developer.chrome.com/docs/lighthouse/performance/total-byte-weight"],
  lhDom: ["Lighthouse: Avoid an excessive DOM size", "https://developer.chrome.com/docs/lighthouse/performance/dom-size"],
  mozTitle: ["Moz: Title tag", "https://moz.com/learn/seo/title-tag"],
  mozDesc: ["Moz: Meta description", "https://moz.com/learn/seo/meta-description"],
  mozDup: ["Moz: Duplicate content", "https://moz.com/learn/seo/duplicate-content"],
  ahrefsH1: ["Ahrefs: The H1 tag", "https://ahrefs.com/blog/h1-tag/"],
  ahrefsInternal: ["Ahrefs: Internal links for SEO", "https://ahrefs.com/blog/internal-links-for-seo/"],
  ahrefsAnchor: ["Ahrefs: Anchor text", "https://ahrefs.com/blog/anchor-text/"],
  ahrefsOrphan: ["Ahrefs: Orphan pages", "https://ahrefs.com/blog/orphan-pages/"],
  openaiBots: ["OpenAI: Bots (GPTBot)", "https://developers.openai.com/api/docs/bots"],
  anthropicBot: ["Anthropic: Does Anthropic crawl the web?", "https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler"],
  perplexityBots: ["Perplexity: PerplexityBot", "https://docs.perplexity.ai/docs/resources/perplexity-crawlers"],
  llmstxt: ["The /llms.txt proposal", "https://llmstxt.org/"],
  ragPaper: ["RAG — Lewis et al., 2020 (arXiv)", "https://arxiv.org/abs/2005.11401"],
  kg: ["Google: Introducing the Knowledge Graph", "https://blog.google/products-and-platforms/products/search/introducing-knowledge-graph-things-not/"],
};

// check id → { tier, confidence (ฐานจาก standard), refs: [REF keys] } · ครบทั้ง 87 checks
const MAP = {
  "title-missing": { tier: 1, confidence: 100, refs: ["gTitle", "htmlTitle"] },
  "title-length": { tier: 3, confidence: 75, refs: ["gTitle", "mozTitle"] },
  "title-duplicate": { tier: 2, confidence: 85, refs: ["gTitle", "mozTitle"] },
  "desc-missing": { tier: 2, confidence: 85, refs: ["gSnippet", "mozDesc"] },
  "desc-length": { tier: 3, confidence: 75, refs: ["gSnippet", "mozDesc"] },
  "desc-duplicate": { tier: 3, confidence: 75, refs: ["gSnippet", "mozDup"] },
  "h1-missing": { tier: 1, confidence: 95, refs: ["htmlHeadings", "gStarter"] },
  "h1-multiple": { tier: 3, confidence: 75, refs: ["htmlHeadings", "ahrefsH1"] },
  "h1-duplicate": { tier: 3, confidence: 70, refs: ["htmlHeadings", "ahrefsH1"] },
  "h1-hidden": { tier: 2, confidence: 80, refs: ["gStarter", "wcagHeadings"] },
  "heading-order": { tier: 1, confidence: 90, refs: ["htmlHeadings", "wcagHeadings"] },
  "empty-headings": { tier: 1, confidence: 90, refs: ["htmlHeadings", "wcagHeadings"] },
  "content-thin": { tier: 2, confidence: 85, refs: ["gHelpful"] },
  "lang-missing": { tier: 1, confidence: 95, refs: ["htmlLang", "wcagLang"] },
  "viewport-missing": { tier: 2, confidence: 85, refs: ["gMobile", "mdnViewport"] },
  "viewport-noscale": { tier: 1, confidence: 90, refs: ["wcagZoom", "mdnViewport"] },
  "favicon-missing": { tier: 2, confidence: 75, refs: ["gFavicon"] },
  "favicon-file": { tier: 2, confidence: 70, refs: ["gFavicon"] },
  "doctype-missing": { tier: 1, confidence: 100, refs: ["htmlDoctype"] },
  "charset-not-utf8": { tier: 1, confidence: 95, refs: ["encoding", "htmlCharset"] },
  "meta-keywords": { tier: 2, confidence: 85, refs: ["gNoKeywords"] },
  "deprecated-tags": { tier: 1, confidence: 90, refs: ["htmlObsolete"] },
  "url-hygiene": { tier: 2, confidence: 80, refs: ["gUrl", "rfc3986"] },
  "copyright-stale": { tier: 3, confidence: 60, refs: ["gHelpful"] },
  "canonical-missing": { tier: 1, confidence: 100, refs: ["gCanonical", "rfc6596"] },
  "canonical-multiple": { tier: 2, confidence: 90, refs: ["gCanonical"] },
  "canonical-relative": { tier: 2, confidence: 80, refs: ["gCanonical", "rfc6596"] },
  "crawl-blocked": { tier: 2, confidence: 90, refs: ["gCrawlers", "gRobotsIntro"] },
  "error-pages": { tier: 1, confidence: 95, refs: ["rfc9110", "gHttpErrors"] },
  "host-variants": { tier: 2, confidence: 85, refs: ["gCanonical"] },
  "hreflang": { tier: 1, confidence: 90, refs: ["gHreflang"] },
  "meta-refresh": { tier: 2, confidence: 85, refs: ["gRedirects", "htmlRefresh"] },
  "near-duplicate": { tier: 2, confidence: 80, refs: ["gCanonical", "mozDup"] },
  "no-pages": { tier: 1, confidence: 100, refs: ["rfc9110", "gHttpErrors"] },
  "noindex": { tier: 1, confidence: 95, refs: ["gBlockIndex", "gRobotsMeta"] },
  "redirect-chain": { tier: 1, confidence: 95, refs: ["gRedirects", "rfc9110redir"] },
  "robots-blocks-all": { tier: 1, confidence: 95, refs: ["rfc9309", "gRobotsIntro"] },
  "robots-blocks-section": { tier: 2, confidence: 85, refs: ["rfc9309", "gRobotsIntro"] },
  "robots-meta-invalid": { tier: 1, confidence: 90, refs: ["gRobotsMeta"] },
  "robots-missing": { tier: 1, confidence: 100, refs: ["rfc9309", "gRobotsIntro"] },
  "robots-sitemap": { tier: 2, confidence: 80, refs: ["sitemapsOrg", "gSitemapOverview"] },
  "sitemap-coverage": { tier: 2, confidence: 80, refs: ["gSitemapOverview"] },
  "sitemap-exists": { tier: 1, confidence: 95, refs: ["sitemapsOrg", "gSitemapBuild"] },
  "sitemap-lastmod": { tier: 2, confidence: 80, refs: ["sitemapsOrg"] },
  "soft-404": { tier: 2, confidence: 90, refs: ["gHttpErrors"] },
  "trailing-slash": { tier: 2, confidence: 80, refs: ["gUrl", "gCanonical"] },
  "broken-links": { tier: 1, confidence: 90, refs: ["rfc9110_404", "gLinks"] },
  "broken-links-soft": { tier: 2, confidence: 80, refs: ["gHttpErrors"] },
  "empty-anchor": { tier: 1, confidence: 85, refs: ["wcagLink", "gLinks"] },
  "generic-anchor": { tier: 3, confidence: 70, refs: ["gLinks", "ahrefsAnchor"] },
  "internal-links-few": { tier: 3, confidence: 70, refs: ["ahrefsInternal", "gLinks"] },
  "orphan-pages": { tier: 3, confidence: 70, refs: ["ahrefsOrphan", "gLinks"] },
  "jsonld-missing": { tier: 1, confidence: 100, refs: ["gStructured", "schemaOrg", "jsonld"] },
  "jsonld-invalid": { tier: 1, confidence: 100, refs: ["jsonld", "gStructured"] },
  "schema-org": { tier: 2, confidence: 85, refs: ["gOrg", "schemaOrgType"] },
  "schema-breadcrumb": { tier: 2, confidence: 85, refs: ["gBreadcrumb", "schemaBreadcrumb"] },
  "schema-incomplete": { tier: 2, confidence: 85, refs: ["gStructured", "schemaOrg"] },
  "og-tags": { tier: 3, confidence: 80, refs: ["ogp"] },
  "og-image-relative": { tier: 3, confidence: 80, refs: ["ogp"] },
  "twitter-card": { tier: 3, confidence: 70, refs: ["xcards"] },
  "https": { tier: 1, confidence: 100, refs: ["gHttps", "rfc9110"] },
  "mixed-content": { tier: 1, confidence: 100, refs: ["mixedW3C", "mdnMixed"] },
  "security-headers": { tier: 2, confidence: 85, refs: ["mdnHeaders", "owasp"] },
  "ssl-chain-incomplete": { tier: 1, confidence: 95, refs: ["rfc8446", "mdnTls"] },
  "ttfb-slow": { tier: 2, confidence: 90, refs: ["wTtfb", "gCwv"] },
  "compression": { tier: 2, confidence: 85, refs: ["lhCompress"] },
  "html-size": { tier: 2, confidence: 80, refs: ["lhPayload"] },
  "inline-bloat": { tier: 3, confidence: 70, refs: ["lhRenderBlock", "lhPayload"] },
  "script-count": { tier: 3, confidence: 70, refs: ["lhDom"] },
  "head-blocking": { tier: 2, confidence: 85, refs: ["lhRenderBlock"] },
  "third-party": { tier: 2, confidence: 80, refs: ["lhThirdParty"] },
  "text-ratio": { tier: 3, confidence: 60, refs: ["lhPayload"] },
  "img-alt": { tier: 1, confidence: 100, refs: ["htmlAlt", "wcagAlt"] },
  "img-dimensions": { tier: 2, confidence: 80, refs: ["htmlImgDim", "gCwv"] },
  "img-lazy": { tier: 3, confidence: 75, refs: ["htmlLazy", "mdnLazy"] },
  "render-diff": { tier: 2, confidence: 85, refs: ["gJsRendering"] },
  "spa-shell": { tier: 2, confidence: 85, refs: ["gJsRendering"] },
  "noscript-fallback": { tier: 2, confidence: 80, refs: ["htmlNoscript", "gJsRendering"] },
  "geo-llms-txt": { tier: 4, confidence: 60, refs: ["llmstxt"] },
  "geo-bot-access": { tier: 4, confidence: 75, refs: ["openaiBots", "anthropicBot", "perplexityBots"] },
  "geo-faq-schema": { tier: 4, confidence: 60, refs: ["gFaq", "schemaFaq"] },
  "geo-qa-content": { tier: 4, confidence: 55, refs: ["ragPaper"] },
  "geo-eeat": { tier: 2, confidence: 80, refs: ["gHelpful", "gQrg"] },
  "geo-citable": { tier: 4, confidence: 55, refs: ["ragPaper"] },
  "geo-entity": { tier: 4, confidence: 55, refs: ["kg", "ragPaper"] },
  "geo-trust-pages": { tier: 4, confidence: 65, refs: ["gQrg", "gHelpful"] },
  "geo-spa-risk": { tier: 4, confidence: 70, refs: ["gJsRendering", "openaiBots"] },
  "cwv-score": { tier: 2, confidence: 90, refs: ["gCwv", "wTtfb"] },
  "cwv-field": { tier: 2, confidence: 90, refs: ["gCwv"] },
};

// referenceFor('title-missing') → { checkId, tier, type, confidence, sources:[{label,url}] }
export function referenceFor(checkId) {
  const m = MAP[checkId];
  if (!m) return null;
  return {
    checkId,
    tier: m.tier,
    type: TIER_TYPE[m.tier],
    confidence: m.confidence,
    sources: (m.refs || []).map(k => REF[k]).filter(Boolean).map(([label, url]) => ({ label, url })),
  };
}

export const REFERENCE_IDS = Object.keys(MAP);
export const hasReference = (id) => MAP[id] != null;
export default { referenceFor, TIER_TYPE, REFERENCE_IDS, hasReference };
